### ISSUE TITLE
Provide branch v1 for gopkg.in

### ISSUE THREAD

**Issue by SommerEngineering** [SommerEngineering/Ocean#31]
### TODOs
- [ ] Create an new branch v1 out of master
- [ ] Do not work any longer on master
- [ ] Change all of Ocean's imports to gopkg.in
- [ ] Create an new branch v2 as copy of v1
- [ ] Further work occurs on v2 instead of master or v1
- [ ] Bugfixing v1 is fine if no API changes

**Comment by SommerEngineering** [comment]
Closed.
