### ISSUE TITLE
Provide proper documentation and examples, etc.

### ISSUE THREAD

**Issue by SommerEngineering** [SommerEngineering/Ocean#32]
### TODOs
- [ ] Check all packages for a proper documentation
- [ ] Provide a main description for GitHub
- [ ] Provide proper examples

**Comment by SommerEngineering** [comment]
Done.
